# Generated by Django 3.1.1 on 2020-10-24 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddToDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_name', models.EmailField(max_length=254)),
                ('pdf', models.FileField(upload_to='books/pdfs/')),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
